/*
 *  This JavaScript file for Dialog JavaScript component
 *  this component works for GnimJS
 *  Version 0.1.8
 *  Write by Ming
 *  Date 2012.03.15
 */
(function(u,d,i,K){function f(a){return a==K||a==i?!0:!1}function l(){var a=d("body")[0],b=d("html")[0];return{st:0==b.scrollTop?a.scrollTop:b.scrollTop,sl:0==b.scrollLeft?a.scrollLeft:b.scrollLeft,sw:b.scrollWidth,sh:b.scrollHeight,cw:b.clientWidth,ch:b.clientHeight}}function m(){d(k+"."+o).css({display:"none"});if(0<v()){var a=l();d(k+"."+o).css({width:a.sw+"px",height:a.sh+"px",display:q?"block":"none"})}}function w(a,b){var c=g.obj.left+a.x-g.x,f=g.obj.top+a.y-g.y,r=d("#"+g.obj.id),e=l(),i=e.sw-
r[0].clientWidth-h-2*j,e=e.sh-r[0].clientHeight-h-2*j,c=c>i?i:c,f=f>e?e:f,c=c<h?h:c,f=f<h?h:f;r.css({left:c+"px",top:f+"px"});b&&(g.obj.left=c,g.obj.top=f)}function v(){var a=0;if(f(e))return 0;for(var b in e)a++;return a}function x(a){if(a){if(!f(e[a]))return e[a].close(),delete e[a],!0}else{for(var b in e)e[b].close(),delete e[b];return!0}return!1}function n(a,b){n.init();var c=this,e;for(e in y)c[e]=y[e];c.id=b;c.isClosed=!1;d('<div id="'+b+'" class="'+s+'"><div class="'+z+'"><div class="'+A+'"></div><div class="'+
B+'"></div></div><div class="'+t+'"></div></div>').appendTo(k+"."+C);f(a)||(a.left=a.left||0,a.top=a.top||0,c.setConfig(a));d("#"+b+"."+B).click(function(a){d.noBubble(a);c.close()});d("#"+b+"."+z).mousedown(function(a){d.broswer.msie?d("body")[0].unselectable="on":d("body").css({"-webkit-user-select":"none","-moz-user-select":"none","-khtml-user-select":"none"});a.preventDefault&&a.preventDefault();g={x:a.clientX,y:a.clientY};g.obj=c;d("#"+c.id).addClass(D)})}function L(a,b){var a=f(a)?this.width:
a,b=f(b)?this.height:b,c=l();0>=a?a=E:1>=a&&(a=(0==c.cw?c.sw-c.sl:c.cw)*a-2*j);0>=b?b=F:1>=b&&(b=(0==c.ch?c.sh-c.st:c.ch)*b-2*j);a=this.width=a==p?a:a+"px";b=this.height=b==p?b:b+"px";d("#"+this.id).css({width:a});d("#"+this.id+"."+t).css({height:b})}function M(a,b){var c=d("#"+this.id),e=l();if(f(a))a=this.left;else{var g=e.sw-c[0].clientWidth-h-2*j,a=a>g?g:a;this.left=a=a<h?h:a}f(b)?b=this.top:(c=e.sh-c[0].clientHeight-h-2*j,b=b>c?c:b,this.top=b=b<h?h:b);d("#"+this.id).css({left:a+"px",top:b+"px"})}
var p="auto",h=0,j=1,E=350,F=p,o="dialog-mask",C="dialog-items",s="dialog-item",D=s+"-draging",N=s+"-",z="dialog-title",A="dialog-title-text",B="dialog-title-close",t="dialog-content",G=!1,g=i,O=0,e={},k="body",q=!0,H=0.2,I={VAL_AUTO:p,POSITION_LEFT_TOP:0,POSITION_LEFT_CENTER:1,POSITION_LEFT_BOTTOM:2,POSITION_CENTER_TOP:3,POSITION_CENTER_CENTER:4,POSITION_CENTER_BOTTOM:5,POSITION_RIGHT_TOP:6,POSITION_RIGHT_CENTER:7,POSITION_RIGHT_BOTTOM:8,dragOpacity:0.9,maskOpacity:function(a){var b=k;return!f(b)?
(f(a)||(a=parseFloat(a),1>=a&&0<=a&&d(b+"."+o).css({opacity:H=a})),H):i},hasMask:function(a){f(a)||(q=!!a);m();return q},dialogCnt:v,getDialog:function(a){return!f(e[a])?e[a]:i},open:function(a,b){f(b)&&(b=N+O++);x(b);var c=new n(a,b);e[b]=c;m();return c},close:x,init:function(a){if(!G){var a=f(a)?k:a,b=d(a);if(1!=b.length)throw Error("selector should find only one element");k=a;e={};"body"!=a&&(b.empty()[0].className="dialog-con");d('<div class="'+o+'"></div>').css({opacity:0.2,display:"none"}).appendTo(b);
d('<div class="'+C+'"></div>').appendTo(b);m();u.onresize=function(){m()};d("body").mousemove(function(a){if(!f(g)){a.preventDefault&&a.preventDefault();w({x:a.clientX,y:a.clientY})}}).mouseup(function(a){if(!f(g)){d.broswer.msie?d("body")[0].unselectable="off":d("body").css({"-webkit-user-select":"","-moz-user-select":"","-khtml-user-select":""});a.preventDefault&&a.preventDefault();w({x:a.clientX,y:a.clientY},true);d("#"+g.obj.id).removeClass(D);g=i}});G=!0}}},y={left:0,top:0,width:E,height:F,listener:i,
id:i};n.prototype={setConfig:function(a){if(!f(a)){for(var b in a){var c=a[b];f(c)||("title"==b?this.title(c):"content"==b?this.content(c):"listener"==b&&(this[b]=c))}this.size(a.width,a.height);this.position(a.left,a.top,a.mode)}},position:function(a,b,c){var c=f(c)?4:c,e=parseInt(c/3),c=c%3,g=d("#"+this.id),h=l();if(!f(a)){var i=h.cw-g[0].clientWidth-2*j;switch(e){case 0:a+=0;break;case 1:a+=i/2;break;case 2:a+=i}a+=h.sl}if(!f(b)){e=h.ch-g[0].clientHeight-2*j;switch(c){case 0:b+=0;break;case 1:b+=
e/2;break;case 2:b+=e}b+=h.st}M.apply(this,[a,b])},size:function(a,b){L.apply(this,[a,b])},title:function(a){var b=d("#"+this.id+"."+A);a&&(a=d.isStr(a)?d(d.build(a)):d(a),b.empty().append(a));return b},content:function(a){var b=d("#"+this.id+"."+t);a&&(a=d.isStr(a)?d(d.build(a)):d(a),b.empty().append(a));return b},close:function(){if(!this.listener||!this.listener()){d("#"+this.id).remove();e[this.id]=i;delete e[this.id];for(var a in this)delete this[a];this.isClosed=!0;m()}},$dom:function(){return d("#"+
this.id)}};for(var J in I)n[J]=I[J];u.NutDialog=n})(window,Gnim,null);
